<?php
/**
 * Created by PhpStorm.
 * User: chesv
 * Date: 01/04/2019
 * Time: 16:09
 */

defined("MODEL_NOT_FOUND_ERROR_CODE") or define("MODEL_NOT_FOUND_ERROR_CODE",1002);
defined("HTTP_NOT_FOUND_ERROR_CODE") or define("HTTP_NOT_FOUND_ERROR_CODE",1003);
defined("PRODUCT_DOES_NOT_BELONG_TO_USER_ERROR_CODE") or define("PRODUCT_DOES_NOT_BELONG_TO_USER_ERROR_CODE",1003);